import { Contact, User, Deal, Automation, Task, EventItem, ChatMessage, Campaign } from "./types";

export const MOCK_USERS: User[] = [
  {
    id: "user-1",
    name: "Aman Sharma",
    email: "aman@flowdesk.ai",
    role: "ADMIN",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    territory: "North & West",
    activeLeadsCount: 24,
  },
  {
    id: "user-2",
    name: "Rahul Kumar",
    email: "rahul@flowdesk.ai",
    role: "SALES",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    territory: "Punjab & Haryana",
    activeLeadsCount: 42,
  },
  {
    id: "user-3",
    name: "Priya Patel",
    email: "priya@flowdesk.ai",
    role: "SALES",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    territory: "Delhi NCR & Mumbai",
    activeLeadsCount: 38,
  },
  {
    id: "user-4",
    name: "Sarah Wilson",
    email: "sarah@flowdesk.ai",
    role: "MARKETING",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    territory: "International",
    activeLeadsCount: 15,
  },
];

export const MOCK_CONTACTS: Contact[] = [
  {
    id: "cont-1",
    name: "John Smith",
    email: "john@abctechnologies.com",
    phone: "+91 98765 43210",
    company: "ABC Technologies Pvt Ltd",
    title: "Managing Director",
    source: "EXCEL_IMPORT",
    status: "INTERESTED",
    leadScore: 88,
    location: "Mumbai, India",
    customFields: {
      productInterest: "Website Redesign & WhatsApp API",
      budget: "₹1,50,000",
      companySize: "50-100",
    },
    assignedToId: "user-2",
    assignedTo: MOCK_USERS[1],
    tags: [
      { id: "tag-1", name: "Hot Lead", color: "#EF4444" },
      { id: "tag-2", name: "Website", color: "#3B82F6" },
      { id: "tag-3", name: "High Value", color: "#10B981" },
    ],
    unreadCount: 1,
    createdAt: "2026-08-20T10:30:00Z",
    updatedAt: "2026-08-24T08:15:00Z",
    lastContactedAt: "Today at 09:30 AM via WhatsApp",
  },
  {
    id: "cont-2",
    name: "Rahul Mehra",
    email: "rahul.mehra@apexinfra.in",
    phone: "+91 98112 88990",
    company: "Apex Infra Developers",
    title: "Chief Executive Officer",
    source: "OCR_SCAN",
    status: "FOLLOW_UP",
    leadScore: 92,
    location: "Gurugram, India",
    customFields: {
      productInterest: "CRM & Multi-Channel Campaigns",
      budget: "₹3,00,000",
    },
    assignedToId: "user-3",
    assignedTo: MOCK_USERS[2],
    tags: [
      { id: "tag-1", name: "Hot Lead", color: "#EF4444" },
      { id: "tag-4", name: "Real Estate", color: "#8B5CF6" },
    ],
    unreadCount: 2,
    createdAt: "2026-08-21T14:20:00Z",
    updatedAt: "2026-08-24T09:00:00Z",
    lastContactedAt: "Yesterday at 04:15 PM via Email",
  },
  {
    id: "cont-3",
    name: "Sarah Jenkins",
    email: "sarah.j@globallogistics.co",
    phone: "+1 (555) 234-5678",
    company: "Global Logistics Corp",
    title: "VP of Operations",
    source: "WEB_FORM",
    status: "QUALIFIED",
    leadScore: 78,
    location: "California, USA",
    customFields: {
      productInterest: "Automation Builder & Webhooks",
      budget: "$5,000/mo",
    },
    assignedToId: "user-1",
    assignedTo: MOCK_USERS[0],
    tags: [
      { id: "tag-5", name: "Enterprise", color: "#F59E0B" },
      { id: "tag-6", name: "USA", color: "#6366F1" },
    ],
    createdAt: "2026-08-18T11:00:00Z",
    updatedAt: "2026-08-23T15:30:00Z",
    lastContactedAt: "Aug 22 via Email",
  },
  {
    id: "cont-4",
    name: "David Brown",
    email: "david@skylineauto.com",
    phone: "+91 97123 45678",
    company: "Skyline Auto Solutions",
    title: "Founder",
    source: "EXCEL_IMPORT",
    status: "CONVERTED",
    leadScore: 95,
    location: "Bangalore, India",
    customFields: {
      productInterest: "WhatsApp Automated Lead Recovery",
      budget: "₹85,000",
    },
    assignedToId: "user-2",
    assignedTo: MOCK_USERS[1],
    tags: [
      { id: "tag-7", name: "Customer", color: "#10B981" },
      { id: "tag-8", name: "Automotive", color: "#EC4899" },
    ],
    createdAt: "2026-08-10T09:00:00Z",
    updatedAt: "2026-08-24T07:45:00Z",
    lastContactedAt: "Aug 23 via WhatsApp",
  },
  {
    id: "cont-5",
    name: "Ananya Deshmukh",
    email: "ananya@fintechpulse.io",
    phone: "+91 99887 76655",
    company: "Fintech Pulse",
    title: "Head of Growth",
    source: "GOOGLE_SHEETS",
    status: "NEW",
    leadScore: 65,
    location: "Pune, India",
    customFields: {
      productInterest: "Event Webinar Reminders",
      budget: "₹50,000",
    },
    assignedToId: "user-3",
    assignedTo: MOCK_USERS[2],
    tags: [{ id: "tag-9", name: "Event Attendee", color: "#06B6D4" }],
    createdAt: "2026-08-24T06:00:00Z",
    updatedAt: "2026-08-24T06:00:00Z",
  },
  {
    id: "cont-6",
    name: "Vikram Malhotra",
    email: "vikram@malhotratextiles.in",
    phone: "+91 98450 11223",
    company: "Malhotra Textiles & Retail",
    title: "Director",
    source: "EXCEL_IMPORT",
    status: "CONTACTED",
    leadScore: 72,
    location: "Ludhiana, India",
    customFields: {
      productInterest: "Broadcast WhatsApp Marketing",
      budget: "₹1,20,000",
    },
    assignedToId: "user-2",
    assignedTo: MOCK_USERS[1],
    tags: [
      { id: "tag-1", name: "Hot Lead", color: "#EF4444" },
      { id: "tag-10", name: "Retail", color: "#F97316" },
    ],
    createdAt: "2026-08-22T13:10:00Z",
    updatedAt: "2026-08-24T08:30:00Z",
    lastContactedAt: "Today at 08:30 AM via WhatsApp",
  },
];

export const MOCK_TIMELINE: Record<string, any[]> = {
  "cont-1": [
    {
      id: "tl-1",
      type: "WHATSAPP_SENT",
      title: "Automated WhatsApp Sent",
      description: "Delivered welcome message template 'website_inquiry_intro' via Official WhatsApp API.",
      createdAt: "Today, 09:30 AM",
      userName: "FlowDesk Automation",
      channel: "WHATSAPP",
    },
    {
      id: "tl-2",
      type: "TASK_CREATED",
      title: "Follow-up Task Assigned",
      description: "Task: 'Call John Smith to discuss customized website proposal' assigned to Rahul Kumar.",
      createdAt: "Today, 09:31 AM",
      userName: "FlowDesk Automation",
      channel: "TASK",
    },
    {
      id: "tl-3",
      type: "EMAIL_OPENED",
      title: "Proposal Email Opened",
      description: "Customer opened 'FlowDesk AI Capabilities & Pricing Deck.pdf' 2 times.",
      createdAt: "Yesterday, 03:45 PM",
      userName: "System Tracker",
      channel: "EMAIL",
    },
    {
      id: "tl-4",
      type: "STATUS_CHANGED",
      title: "Status changed to Interested",
      description: "Lead score updated from 65 ➔ 88 based on email engagement.",
      createdAt: "Aug 22, 02:10 PM",
      userName: "Rahul Kumar",
      channel: "SYSTEM",
    },
    {
      id: "tl-5",
      type: "IMPORTED",
      title: "Imported from 500_leads.xlsx",
      description: "Auto-mapped 5 columns, normalized phone number to +91 98765 43210.",
      createdAt: "Aug 20, 10:30 AM",
      userName: "Smart Importer",
      channel: "SYSTEM",
    },
  ],
};

export const MOCK_DEALS: Deal[] = [
  {
    id: "deal-1",
    title: "ABC Tech Website + WhatsApp Suite",
    contactId: "cont-1",
    contactName: "John Smith",
    company: "ABC Technologies",
    value: 150000,
    stage: "PROPOSAL",
    probability: 75,
    expectedCloseDate: "2026-09-05",
    assignedToName: "Rahul Kumar",
  },
  {
    id: "deal-2",
    title: "Apex Infra Multi-Channel Marketing",
    contactId: "cont-2",
    contactName: "Rahul Mehra",
    company: "Apex Infra Developers",
    value: 300000,
    stage: "NEGOTIATION",
    probability: 85,
    expectedCloseDate: "2026-08-31",
    assignedToName: "Priya Patel",
  },
  {
    id: "deal-3",
    title: "Global Logistics Enterprise Automation",
    contactId: "cont-3",
    contactName: "Sarah Jenkins",
    company: "Global Logistics Corp",
    value: 450000,
    stage: "DISCOVERY",
    probability: 40,
    expectedCloseDate: "2026-09-20",
    assignedToName: "Aman Sharma",
  },
  {
    id: "deal-4",
    title: "Skyline Auto Annual License",
    contactId: "cont-4",
    contactName: "David Brown",
    company: "Skyline Auto Solutions",
    value: 85000,
    stage: "WON",
    probability: 100,
    expectedCloseDate: "2026-08-23",
    assignedToName: "Rahul Kumar",
  },
];

export const MOCK_AUTOMATIONS: Automation[] = [
  {
    id: "auto-1",
    name: "New Lead 360° Follow-up Engine",
    description: "When a new lead is imported, instantly assign rep, send WhatsApp, wait 1 day, send email, and create a follow-up task.",
    status: "ACTIVE",
    category: "SALES",
    triggerType: "CONTACT_CREATED",
    executionCount: 1240,
    successCount: 1218,
    failureCount: 22,
    lastRunAt: "5 minutes ago",
    flowDefinition: {
      nodes: [
        {
          id: "node-1",
          type: "trigger",
          position: { x: 250, y: 50 },
          data: {
            label: "New Customer Added",
            type: "trigger",
            description: "Triggers on Excel import, Form submit or OCR scan",
            config: { event: "CONTACT_CREATED" },
          },
        },
        {
          id: "node-2",
          type: "action_assign",
          position: { x: 250, y: 180 },
          data: {
            label: "Assign Lead (Round Robin)",
            type: "action_assign",
            description: "Evenly distributes to active sales team",
            config: { method: "Round-Robin", team: "Sales Team" },
          },
        },
        {
          id: "node-3",
          type: "action_whatsapp",
          position: { x: 250, y: 310 },
          data: {
            label: "Send WhatsApp Intro",
            type: "action_whatsapp",
            description: "Hi {{name}} 👋 Thanks for your interest in {{product}}",
            config: {
              templateName: "lead_welcome_intro",
              message: "Hi {{name}} 👋 Thanks for reaching out! Our team is reviewing your requirements.",
            },
          },
        },
        {
          id: "node-4",
          type: "delay",
          position: { x: 250, y: 440 },
          data: {
            label: "Wait 1 Day",
            type: "delay",
            description: "Pauses execution for 24 hours",
            config: { duration: 1, unit: "days" },
          },
        },
        {
          id: "node-5",
          type: "action_email",
          position: { x: 250, y: 570 },
          data: {
            label: "Send Intro Deck Email",
            type: "action_email",
            description: "Sends catalog & presentation with open tracking",
            config: {
              subject: "FlowDesk AI — Overview & Next Steps for {{company}}",
              template: "sales_presentation_v2",
            },
          },
        },
        {
          id: "node-6",
          type: "action_task",
          position: { x: 250, y: 700 },
          data: {
            label: "Create Follow-up Task",
            type: "action_task",
            description: "Creates high priority task for assigned salesperson",
            config: {
              title: "Call {{name}} for discovery demo",
              priority: "HIGH",
              dueDays: 1,
            },
          },
        },
      ],
      edges: [
        { id: "e1-2", source: "node-1", target: "node-2", animated: true },
        { id: "e2-3", source: "node-2", target: "node-3", animated: true },
        { id: "e3-4", source: "node-3", target: "node-4", animated: true },
        { id: "e4-5", source: "node-4", target: "node-5", animated: true },
        { id: "e5-6", source: "node-5", target: "node-6", animated: true },
      ],
    },
  },
  {
    id: "auto-2",
    name: "AI Workshop & Webinar Auto-Reminders",
    description: "Event registration workflow with multi-step WhatsApp + Email reminders and post-event survey.",
    status: "ACTIVE",
    category: "EVENTS",
    triggerType: "EVENT_REGISTERED",
    executionCount: 560,
    successCount: 558,
    failureCount: 2,
    lastRunAt: "22 mins ago",
    flowDefinition: {
      nodes: [
        {
          id: "w-1",
          type: "trigger",
          position: { x: 250, y: 50 },
          data: {
            label: "Event Registered",
            type: "trigger",
            description: "Customer registers for AI Webinar",
            config: { event: "EVENT_REGISTERED" },
          },
        },
        {
          id: "w-2",
          type: "action_whatsapp",
          position: { x: 250, y: 180 },
          data: {
            label: "WhatsApp Confirmation + Calendar",
            type: "action_whatsapp",
            description: "Instant pass & join link sent via WhatsApp",
            config: { templateName: "event_pass_confirmation" },
          },
        },
        {
          id: "w-3",
          type: "delay",
          position: { x: 250, y: 310 },
          data: {
            label: "Wait until 2 Hours Before Event",
            type: "delay",
            description: "Dynamic countdown trigger",
            config: { duration: 2, unit: "hours_before" },
          },
        },
        {
          id: "w-4",
          type: "action_whatsapp",
          position: { x: 250, y: 440 },
          data: {
            label: "Send 2-Hour WhatsApp Reminder",
            type: "action_whatsapp",
            description: "We are starting in 2 hours! Tap to join.",
            config: { templateName: "event_urgent_reminder" },
          },
        },
      ],
      edges: [
        { id: "we1-2", source: "w-1", target: "w-2", animated: true },
        { id: "we2-3", source: "w-2", target: "w-3", animated: true },
        { id: "we3-4", source: "w-3", target: "w-4", animated: true },
      ],
    },
  },
  {
    id: "auto-3",
    name: "Old Lead Recovery & Re-engagement",
    description: "Reaches out to leads inactive for 60+ days with custom offer.",
    status: "ERROR",
    category: "MARKETING",
    triggerType: "CUSTOMER_INACTIVE",
    executionCount: 310,
    successCount: 288,
    failureCount: 22,
    lastRunAt: "1 hour ago",
    flowDefinition: {
      nodes: [
        {
          id: "r-1",
          type: "trigger",
          position: { x: 250, y: 50 },
          data: {
            label: "Customer Inactive > 60 Days",
            type: "trigger",
            config: { days: 60 },
          },
        },
        {
          id: "r-2",
          type: "action_whatsapp",
          position: { x: 250, y: 180 },
          data: {
            label: "Send Special Re-engagement Offer",
            type: "action_whatsapp",
            config: { templateName: "special_winback_offer" },
          },
        },
      ],
      edges: [{ id: "re1-2", source: "r-1", target: "r-2", animated: true }],
    },
  },
];

export const MOCK_AUTOMATION_TEMPLATES = [
  {
    id: "tpl-1",
    category: "SALES",
    name: "New Lead Instant Follow-up",
    description: "Instant WhatsApp greeting → Assign to Sales Rep → Email presentation → Sales Task.",
    icon: "Zap",
    recommended: true,
  },
  {
    id: "tpl-2",
    category: "SALES",
    name: "Hot Lead VIP Fast-Track",
    description: "If Lead Score > 75: Alert Senior Account Exec on Slack & send priority WhatsApp.",
    icon: "Flame",
    recommended: true,
  },
  {
    id: "tpl-3",
    category: "EVENTS",
    name: "Event & Webinar 4-Step Journey",
    description: "Registration confirmation → 2-day reminder → 2-hour WhatsApp alert → Post-event feedback.",
    icon: "Calendar",
    recommended: true,
  },
  {
    id: "tpl-4",
    category: "MARKETING",
    name: "Welcome Onboarding Sequence",
    description: "3-part educational email sequence spaced across 7 days with interactive buttons.",
    icon: "Mail",
    recommended: false,
  },
  {
    id: "tpl-5",
    category: "ECOMMERCE",
    name: "Abandoned Cart WhatsApp Recovery",
    description: "Detects cart drop-off → Sends WhatsApp with 10% coupon link within 30 minutes.",
    icon: "ShoppingCart",
    recommended: false,
  },
  {
    id: "tpl-6",
    category: "SALES",
    name: "Missed Call / Inquiry Auto-Reply",
    description: "Instant WhatsApp reply: 'Sorry we missed your call! How can we assist you today?'",
    icon: "PhoneCall",
    recommended: false,
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "task-1",
    title: "Call John Smith regarding website proposal",
    description: "Customer viewed pricing deck twice. Follow up on custom API requirements.",
    contactId: "cont-1",
    contactName: "John Smith",
    contactCompany: "ABC Technologies",
    dueDate: "Today, 02:00 PM",
    priority: "HIGH",
    status: "PENDING",
    assignedToId: "user-2",
    assignedTo: MOCK_USERS[1],
  },
  {
    id: "task-2",
    title: "Send revised proposal to Rahul Mehra",
    description: "Add multi-branch CRM license option requested during yesterday's meeting.",
    contactId: "cont-2",
    contactName: "Rahul Mehra",
    contactCompany: "Apex Infra",
    dueDate: "Today, 04:30 PM",
    priority: "URGENT",
    status: "PENDING",
    assignedToId: "user-3",
    assignedTo: MOCK_USERS[2],
  },
  {
    id: "task-3",
    title: "Prepare Zoom demo for Sarah Jenkins",
    description: "Focus on BullMQ queue architecture and webhook custom payload mapping.",
    contactId: "cont-3",
    contactName: "Sarah Jenkins",
    contactCompany: "Global Logistics",
    dueDate: "Tomorrow, 11:00 AM",
    priority: "MEDIUM",
    status: "PENDING",
    assignedToId: "user-1",
    assignedTo: MOCK_USERS[0],
  },
  {
    id: "task-4",
    title: "Onboarding check-in call with David Brown",
    description: "Confirm WhatsApp template approved by Meta and test first live broadcast.",
    contactId: "cont-4",
    contactName: "David Brown",
    contactCompany: "Skyline Auto",
    dueDate: "Yesterday",
    priority: "LOW",
    status: "COMPLETED",
    assignedToId: "user-2",
    assignedTo: MOCK_USERS[1],
  },
];

export const MOCK_EVENTS: EventItem[] = [
  {
    id: "evt-1",
    title: "AI & WhatsApp Business Growth Masterclass",
    description: "Learn how modern businesses scale lead follow-ups using FlowDesk AI automation.",
    type: "WEBINAR",
    eventDate: "2026-09-15T15:00:00Z",
    durationMins: 60,
    locationUrl: "https://zoom.us/j/flowdesk-ai-masterclass",
    maxCapacity: 500,
    registeredCount: 342,
    confirmedCount: 298,
    attendedCount: 0,
  },
  {
    id: "evt-2",
    title: "Enterprise CRM & Multi-Tenant Architecture Demo",
    description: "Live walkthrough for sales heads and operations directors.",
    type: "DEMO",
    eventDate: "2026-09-02T11:00:00Z",
    durationMins: 45,
    locationUrl: "https://meet.google.com/fd-demo-2026",
    maxCapacity: 50,
    registeredCount: 42,
    confirmedCount: 39,
  },
];

export const MOCK_CHATS: Record<string, ChatMessage[]> = {
  "cont-1": [
    {
      id: "msg-1",
      contactId: "cont-1",
      channel: "WHATSAPP",
      direction: "OUTBOUND",
      status: "READ",
      senderName: "FlowDesk AI",
      content: "Hi John 👋 Thanks for your interest in our website services! We're reviewing your requirements. Are you looking to launch this month?",
      timestamp: "Today, 09:30 AM",
    },
    {
      id: "msg-2",
      contactId: "cont-1",
      channel: "WHATSAPP",
      direction: "INBOUND",
      status: "READ",
      senderName: "John Smith",
      content: "Hi, yes! We have a deadline by mid-next month. Can we integrate the WhatsApp lead capture directly on the new site?",
      timestamp: "Today, 09:42 AM",
    },
    {
      id: "msg-3",
      contactId: "cont-1",
      channel: "WHATSAPP",
      direction: "OUTBOUND",
      status: "DELIVERED",
      senderName: "Rahul Kumar",
      content: "Absolutely, John! That is our specialty. I will call you today at 2:00 PM to walk through the exact setup.",
      timestamp: "Today, 10:05 AM",
    },
  ],
  "cont-2": [
    {
      id: "msg-201",
      contactId: "cont-2",
      channel: "WHATSAPP",
      direction: "OUTBOUND",
      status: "READ",
      senderName: "Priya Patel",
      content: "Hello Mr. Mehra, I have prepared the CRM proposal for Apex Infra with the 5-branch distribution.",
      timestamp: "Yesterday, 04:15 PM",
    },
    {
      id: "msg-202",
      contactId: "cont-2",
      channel: "WHATSAPP",
      direction: "INBOUND",
      status: "READ",
      senderName: "Rahul Mehra",
      content: "Please send the updated pricing by 4:30 PM today so we can finalize.",
      timestamp: "Today, 09:00 AM",
    },
  ],
};

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: "cmp-1",
    name: "Festive Season Flash Promotion",
    channel: "WHATSAPP",
    segmentName: "Hot Leads + Real Estate (Delhi NCR)",
    status: "COMPLETED",
    totalRecipients: 2430,
    sentCount: 2430,
    deliveredCount: 2398,
    readCount: 2180,
    clickedCount: 940,
  },
  {
    id: "cmp-2",
    name: "Q3 Product Update & Feature Showcase",
    channel: "EMAIL",
    segmentName: "All Active Customers",
    status: "COMPLETED",
    totalRecipients: 5800,
    sentCount: 5800,
    deliveredCount: 5740,
    readCount: 3120,
    clickedCount: 1420,
  },
  {
    id: "cmp-3",
    name: "Webinar Masterclass Reminder",
    channel: "WHATSAPP",
    segmentName: "Registered Attendees (AI Masterclass)",
    status: "SCHEDULED",
    scheduledAt: "2026-09-15 13:00",
    totalRecipients: 342,
    sentCount: 0,
    deliveredCount: 0,
    readCount: 0,
    clickedCount: 0,
  },
];
