import {
  Contact,
  User,
  Deal,
  Automation,
  Task,
  EventItem,
  ChatMessage,
  Campaign,
  CustomRole,
  LeadList,
  MessageTemplate,
  AuditLog,
  LeadJourneyStep,
} from "./types";

export const MOCK_CUSTOM_ROLES: CustomRole[] = [
  {
    id: "role-admin",
    name: "Main Admin",
    description: "Unrestricted access across the entire organization, settings, audit logs and billing.",
    isSystem: true,
    permissions: [
      "LEAD_VIEW_ALL", "LEAD_CREATE", "LEAD_EDIT", "LEAD_DELETE", "LEAD_IMPORT", "LEAD_EXPORT", "LEAD_ASSIGN", "LEAD_REASSIGN",
      "CAMPAIGN_CREATE", "CAMPAIGN_LAUNCH", "CAMPAIGN_PAUSE",
      "TEMPLATE_CREATE", "TEMPLATE_APPROVE",
      "WORKFLOW_CREATE", "WORKFLOW_ACTIVATE", "WORKFLOW_PAUSE",
      "ANALYTICS_COMPANY", "ANALYTICS_TEAM", "ANALYTICS_OWN",
      "SETTINGS_MANAGE", "AUDIT_LOG_VIEW",
    ],
  },
  {
    id: "role-manager",
    name: "Sales Pod Manager",
    description: "Manages own subordinate sales team, team leads, team workflows and team analytics.",
    isSystem: true,
    permissions: [
      "LEAD_VIEW_TEAM", "LEAD_CREATE", "LEAD_EDIT", "LEAD_IMPORT", "LEAD_ASSIGN", "LEAD_REASSIGN",
      "CAMPAIGN_CREATE", "CAMPAIGN_LAUNCH", "CAMPAIGN_PAUSE",
      "TEMPLATE_CREATE",
      "WORKFLOW_CREATE", "WORKFLOW_ACTIVATE", "WORKFLOW_PAUSE",
      "ANALYTICS_TEAM", "ANALYTICS_OWN",
    ],
  },
  {
    id: "role-senior-marketing",
    name: "Senior Marketing Employee (Custom)",
    description: "Can create campaigns, workflows and templates, but cannot export or delete customer data.",
    isSystem: false,
    permissions: [
      "LEAD_VIEW_TEAM", "LEAD_CREATE", "LEAD_IMPORT",
      "CAMPAIGN_CREATE", "CAMPAIGN_LAUNCH",
      "TEMPLATE_CREATE",
      "WORKFLOW_CREATE", "WORKFLOW_ACTIVATE",
      "ANALYTICS_TEAM", "ANALYTICS_OWN",
    ],
  },
  {
    id: "role-sales-rep",
    name: "Sales Representative",
    description: "Operates exclusively on assigned leads, personal follow-ups and response inbox.",
    isSystem: true,
    permissions: [
      "LEAD_VIEW_OWN", "LEAD_CREATE", "LEAD_EDIT",
      "ANALYTICS_OWN",
    ],
  },
];

export const MOCK_USERS: User[] = [
  {
    id: "usr-admin",
    name: "Aman Sharma",
    email: "aman@flowdesk.ai",
    role: "MAIN_ADMIN",
    customRoleName: "Main Admin",
    department: "Executive & Growth",
    territory: "Global Head",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    activeLeadsCount: 120,
  },
  {
    id: "usr-mgr-1",
    name: "Rahul Kumar",
    email: "rahul.manager@flowdesk.ai",
    role: "MANAGER",
    customRoleName: "Sales Pod Manager",
    department: "North & West Pod",
    territory: "Punjab, Haryana, Delhi NCR",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    activeLeadsCount: 48,
    managedEmployeeIds: ["usr-emp-1", "usr-emp-2", "usr-emp-3"],
  },
  {
    id: "usr-mgr-2",
    name: "Sarah Wilson",
    email: "sarah.manager@flowdesk.ai",
    role: "MANAGER",
    customRoleName: "Sales Pod Manager",
    department: "Enterprise & International Pod",
    territory: "USA, UK & Corporate",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    activeLeadsCount: 35,
    managedEmployeeIds: ["usr-emp-4", "usr-emp-5"],
  },
  {
    id: "usr-emp-1",
    name: "Priya Patel",
    email: "priya.sales@flowdesk.ai",
    role: "EMPLOYEE",
    customRoleName: "Sales Representative",
    managerId: "usr-mgr-1",
    managerName: "Rahul Kumar",
    department: "North Sales Pod",
    territory: "Delhi NCR & Gurugram",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    activeLeadsCount: 34,
  },
  {
    id: "usr-emp-2",
    name: "Karan Seth",
    email: "karan.sales@flowdesk.ai",
    role: "EMPLOYEE",
    customRoleName: "Sales Representative",
    managerId: "usr-mgr-1",
    managerName: "Rahul Kumar",
    department: "North Sales Pod",
    territory: "Punjab & Chandigarh",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    activeLeadsCount: 28,
  },
  {
    id: "usr-emp-3",
    name: "Neha Roy",
    email: "neha.marketing@flowdesk.ai",
    role: "EMPLOYEE",
    customRoleId: "role-senior-marketing",
    customRoleName: "Senior Marketing Employee (Custom)",
    managerId: "usr-mgr-1",
    managerName: "Rahul Kumar",
    department: "Marketing Operations",
    territory: "National Campaigns",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    activeLeadsCount: 15,
  },
  {
    id: "usr-emp-4",
    name: "David Brown",
    email: "david.enterprise@flowdesk.ai",
    role: "EMPLOYEE",
    customRoleName: "Sales Representative",
    managerId: "usr-mgr-2",
    managerName: "Sarah Wilson",
    department: "Enterprise Pod",
    territory: "North America",
    avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    activeLeadsCount: 22,
  },
];

export const MOCK_LEAD_LISTS: LeadList[] = [
  {
    id: "list-1",
    name: "Real Estate Leads – Punjab",
    description: "Imported luxury apartment & commercial inquiries from Punjab exhibition.",
    createdById: "usr-emp-2",
    createdByName: "Karan Seth",
    createdAt: "Aug 24, 2026",
    leadCount: 500,
    source: "EXCEL_IMPORT",
    assignedWorkflowId: "auto-1",
    assignedWorkflowName: "Response-Based 360° Follow-up Engine",
  },
  {
    id: "list-2",
    name: "Website Inbound Inquiries — Aug 2026",
    description: "Direct captures from FlowDesk demo booking form and WhatsApp entry point.",
    createdById: "usr-admin",
    createdByName: "Aman Sharma",
    createdAt: "Aug 20, 2026",
    leadCount: 240,
    source: "WEB_FORM",
    assignedWorkflowId: "auto-1",
    assignedWorkflowName: "Response-Based 360° Follow-up Engine",
  },
  {
    id: "list-3",
    name: "AI Growth Webinar Signups",
    description: "Registered delegates for Masterclass 2026.",
    createdById: "usr-emp-3",
    createdByName: "Neha Roy",
    createdAt: "Aug 18, 2026",
    leadCount: 342,
    source: "EVENT_SIGNUP",
    assignedWorkflowId: "auto-2",
    assignedWorkflowName: "AI Workshop & Webinar Auto-Reminders",
  },
];

export const MOCK_EVENTS: EventItem[] = [
  {
    id: "evt-1",
    title: "AI & WhatsApp Business Growth Masterclass",
    description: "Learn how modern sales teams scale lead follow-ups using FlowDesk AI automation.",
    type: "WEBINAR",
    eventDate: "2026-09-15T15:00:00Z",
    durationMins: 60,
    locationUrl: "https://zoom.us/j/flowdesk-ai-masterclass",
    maxCapacity: 500,
    registeredCount: 342,
    confirmedCount: 298,
    attendedCount: 0,
  },
  {
    id: "evt-2",
    title: "Enterprise CRM & Multi-Tenant Architecture Demo",
    description: "Live walkthrough for sales heads and operations directors.",
    type: "DEMO",
    eventDate: "2026-09-02T11:00:00Z",
    durationMins: 45,
    locationUrl: "https://meet.google.com/fd-demo-2026",
    maxCapacity: 50,
    registeredCount: 42,
    confirmedCount: 39,
  },
];

export const MOCK_CONTACTS: Contact[] = [
  {
    id: "cont-1",
    name: "Rahul Sharma",
    email: "rahul.sharma@abctech.com",
    phone: "+91 98765 43210",
    company: "ABC Technologies Pvt Ltd",
    title: "Managing Director",
    source: "EXCEL_IMPORT",
    status: "INTERESTED",
    leadScore: 88,
    location: "Ludhiana, Punjab",
    
    createdById: "usr-admin",
    createdByName: "Aman Sharma",
    ownerId: "usr-emp-1",
    ownerName: "Priya Patel",
    managerId: "usr-mgr-1",
    managerName: "Rahul Kumar",
    
    leadListId: "list-1",
    leadListName: "Real Estate Leads – Punjab",
    activeWorkflowId: "auto-1",
    activeWorkflowName: "Response-Based 360° Follow-up Engine",
    doNotContact: false,
    
    tags: [
      { id: "t-1", name: "Hot Lead", color: "#EF4444" },
      { id: "t-2", name: "Website Redesign", color: "#3B82F6" },
      { id: "t-3", name: "Punjab", color: "#10B981" },
    ],
    unreadCount: 1,
    nextFollowUpDate: "Today, 02:00 PM",
    createdAt: "2026-08-20T10:30:00Z",
    updatedAt: "2026-08-24T08:15:00Z",
    lastContactedAt: "Today at 09:30 AM via WhatsApp",
  },
  {
    id: "cont-2",
    name: "Aman Kapoor",
    email: "aman.kapoor@apexinfra.in",
    phone: "+91 98112 88990",
    company: "Apex Infra Developers",
    title: "Chief Executive Officer",
    source: "OCR_SCAN",
    status: "FOLLOW_UP",
    leadScore: 92,
    location: "Gurugram, Delhi NCR",
    
    createdById: "usr-emp-1",
    createdByName: "Priya Patel",
    ownerId: "usr-emp-1",
    ownerName: "Priya Patel",
    managerId: "usr-mgr-1",
    managerName: "Rahul Kumar",
    
    leadListId: "list-1",
    leadListName: "Real Estate Leads – Punjab",
    activeWorkflowId: "auto-1",
    activeWorkflowName: "Response-Based 360° Follow-up Engine",
    doNotContact: false,
    
    tags: [
      { id: "t-1", name: "Hot Lead", color: "#EF4444" },
      { id: "t-4", name: "Real Estate", color: "#8B5CF6" },
    ],
    unreadCount: 2,
    nextFollowUpDate: "Today, 04:30 PM",
    createdAt: "2026-08-21T14:20:00Z",
    updatedAt: "2026-08-24T09:00:00Z",
    lastContactedAt: "Yesterday at 04:15 PM via WhatsApp",
  },
  {
    id: "cont-3",
    name: "Sarah Jenkins",
    email: "sarah.j@globallogistics.co",
    phone: "+1 (555) 234-5678",
    company: "Global Logistics Corp",
    title: "VP of Operations",
    source: "WEB_FORM",
    status: "QUALIFIED",
    leadScore: 78,
    location: "California, USA",
    
    createdById: "usr-admin",
    createdByName: "Aman Sharma",
    ownerId: "usr-emp-4",
    ownerName: "David Brown",
    managerId: "usr-mgr-2",
    managerName: "Sarah Wilson",
    
    leadListId: "list-2",
    leadListName: "Website Inbound Inquiries — Aug 2026",
    doNotContact: false,
    
    tags: [
      { id: "t-5", name: "Enterprise", color: "#F59E0B" },
      { id: "t-6", name: "USA", color: "#6366F1" },
    ],
    createdAt: "2026-08-18T11:00:00Z",
    updatedAt: "2026-08-23T15:30:00Z",
    lastContactedAt: "Aug 22 via Email",
  },
  {
    id: "cont-4",
    name: "Vikram Malhotra",
    email: "vikram@malhotratextiles.in",
    phone: "+91 98450 11223",
    company: "Malhotra Textiles & Retail",
    title: "Director",
    source: "EXCEL_IMPORT",
    status: "CONTACTED",
    leadScore: 72,
    location: "Amritsar, Punjab",
    
    createdById: "usr-emp-2",
    createdByName: "Karan Seth",
    ownerId: "usr-emp-2",
    ownerName: "Karan Seth",
    managerId: "usr-mgr-1",
    managerName: "Rahul Kumar",
    
    leadListId: "list-1",
    leadListName: "Real Estate Leads – Punjab",
    doNotContact: false,
    
    tags: [
      { id: "t-1", name: "Hot Lead", color: "#EF4444" },
      { id: "t-7", name: "Retail", color: "#F97316" },
    ],
    createdAt: "2026-08-22T13:10:00Z",
    updatedAt: "2026-08-24T08:30:00Z",
  },
  {
    id: "cont-5",
    name: "Suresh Chandra",
    email: "suresh@optoutlead.com",
    phone: "+91 99999 00000",
    company: "OptOut Corp",
    source: "MANUAL",
    status: "DO_NOT_CONTACT",
    leadScore: 10,
    location: "Delhi",
    
    createdById: "usr-admin",
    createdByName: "Aman Sharma",
    ownerId: "usr-emp-1",
    ownerName: "Priya Patel",
    managerId: "usr-mgr-1",
    managerName: "Rahul Kumar",
    
    doNotContact: true,
    tags: [{ id: "t-8", name: "Opted Out", color: "#64748B" }],
    createdAt: "2026-08-15T09:00:00Z",
    updatedAt: "2026-08-24T06:00:00Z",
  },
];

export const MOCK_LEAD_JOURNEYS: Record<string, LeadJourneyStep[]> = {
  "cont-1": [
    {
      id: "j-1",
      title: "Lead Ingested & Sanitized",
      description: "Imported via 500_leads.xlsx. Column 'Mobile' auto-mapped to E.164 (+91 98765 43210).",
      timestamp: "Aug 20, 10:30 AM",
      actor: "Aman Sharma (Importer)",
      channel: "SYSTEM",
      status: "COMPLETED",
    },
    {
      id: "j-2",
      title: "Assigned to Sales Rep",
      description: "Assigned to Priya Patel under North Pod (Manager: Rahul Kumar) via Round-Robin.",
      timestamp: "Aug 20, 10:31 AM",
      actor: "FlowDesk Lead Router",
      channel: "SYSTEM",
      status: "COMPLETED",
    },
    {
      id: "j-3",
      title: "Enrolled in 'Response-Based Follow-up Engine'",
      description: "Auto-enrolled in 4-step follow-up automation. Duplicate safeguard check: PASSED.",
      timestamp: "Aug 20, 10:31 AM",
      actor: "Automation Engine",
      channel: "SYSTEM",
      status: "COMPLETED",
    },
    {
      id: "j-4",
      title: "Official WhatsApp Sent",
      description: "Template 'lead_welcome_intro' delivered successfully via Meta WhatsApp Cloud API.",
      timestamp: "Aug 20, 10:32 AM",
      actor: "WhatsApp Cloud API",
      channel: "WHATSAPP",
      status: "COMPLETED",
    },
    {
      id: "j-5",
      title: "Customer Inbound Reply Received",
      description: "Customer replied: 'Yes, I am interested. Please share pricing and website proposal.'",
      timestamp: "Today, 09:42 AM",
      actor: "Rahul Sharma (Customer)",
      channel: "WHATSAPP",
      status: "COMPLETED",
    },
    {
      id: "j-6",
      title: "AI Response Intent Classified: INTERESTED",
      description: "Confidence: 98%. Triggered priority branch: Updated status to INTERESTED and paused drip.",
      timestamp: "Today, 09:43 AM",
      actor: "AI Intent Engine",
      channel: "AI",
      status: "COMPLETED",
    },
    {
      id: "j-7",
      title: "High-Priority Call Task Created",
      description: "Assigned urgent task to Priya Patel: 'Call Rahul Sharma to finalize website contract'. Due: 2 PM.",
      timestamp: "Today, 09:43 AM",
      actor: "FlowDesk Automation",
      channel: "TASK",
      status: "CURRENT",
    },
  ],
};

export const MOCK_TEMPLATES: MessageTemplate[] = [
  {
    id: "tpl-wa-1",
    name: "lead_welcome_intro",
    channel: "WHATSAPP",
    body: "Hi {{first_name}} 👋 Thanks for your interest in {{company_service}}! Our team is reviewing your requirements. Would you like to see a live demo?",
    category: "MARKETING",
    status: "APPROVED",
    isCompanyWide: true,
    createdById: "usr-admin",
    createdByName: "Aman Sharma",
    createdAt: "Aug 15, 2026",
    approvedBy: "Aman Sharma (Admin)",
  },
  {
    id: "tpl-wa-2",
    name: "property_followup_punjab",
    channel: "WHATSAPP",
    body: "Hello {{first_name}}, following up on our 3BHK luxury options in Punjab. Are you available for a site visit this weekend?",
    category: "MARKETING",
    status: "APPROVED",
    isCompanyWide: true,
    createdById: "usr-mgr-1",
    createdByName: "Rahul Kumar",
    createdAt: "Aug 19, 2026",
    approvedBy: "Aman Sharma (Admin)",
  },
  {
    id: "tpl-wa-3",
    name: "diwali_flash_discount",
    channel: "WHATSAPP",
    body: "Celebrate Diwali with 20% off on all FlowDesk licenses! Use code FESTIVE20 today.",
    category: "MARKETING",
    status: "PENDING_APPROVAL",
    isCompanyWide: false,
    createdById: "usr-emp-3",
    createdByName: "Neha Roy",
    createdAt: "Aug 24, 2026",
  },
  {
    id: "tpl-em-1",
    name: "sales_presentation_deck",
    channel: "EMAIL",
    subject: "FlowDesk AI — Overview & Next Steps for {{company}}",
    body: "Hi {{first_name}},\n\nAttached is our comprehensive capability deck. We would love to discuss how our automation platform can save your team 20+ hours every week.\n\nBest regards,\n{{employee_name}}",
    category: "MARKETING",
    status: "APPROVED",
    isCompanyWide: true,
    createdById: "usr-admin",
    createdByName: "Aman Sharma",
    createdAt: "Aug 10, 2026",
    approvedBy: "Aman Sharma (Admin)",
  },
];

export const MOCK_AUTOMATION_TEMPLATES = [
  {
    id: "tpl-1",
    category: "SALES",
    name: "Response-Based New Lead Follow-up",
    description: "WhatsApp greeting → Wait for response → AI classifies intent: if Interested notify manager & create task; if No response send email.",
    icon: "Zap",
    recommended: true,
  },
  {
    id: "tpl-2",
    category: "SALES",
    name: "Hot Lead VIP Fast-Track",
    description: "If Lead Score > 75: Alert Senior Account Exec on Slack & send priority WhatsApp.",
    icon: "Flame",
    recommended: true,
  },
  {
    id: "tpl-3",
    category: "EVENTS",
    name: "Event & Webinar 4-Step Journey",
    description: "Registration confirmation → 2-day reminder → 2-hour WhatsApp alert → Post-event feedback.",
    icon: "Calendar",
    recommended: true,
  },
  {
    id: "tpl-4",
    category: "MARKETING",
    name: "Welcome Onboarding Sequence",
    description: "3-part educational email sequence spaced across 7 days with interactive buttons.",
    icon: "Mail",
    recommended: false,
  },
  {
    id: "tpl-5",
    category: "ECOMMERCE",
    name: "Abandoned Cart WhatsApp Recovery",
    description: "Detects cart drop-off → Sends WhatsApp with 10% coupon link within 30 minutes.",
    icon: "ShoppingCart",
    recommended: false,
  },
  {
    id: "tpl-6",
    category: "SALES",
    name: "Missed Call / Inquiry Auto-Reply",
    description: "Instant WhatsApp reply: 'Sorry we missed your call! How can we assist you today?'",
    icon: "PhoneCall",
    recommended: false,
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: "log-1",
    userId: "usr-admin",
    userName: "Aman Sharma",
    userRole: "MAIN_ADMIN",
    action: "UPDATED_SETTINGS",
    entityType: "SETTINGS",
    entityName: "WhatsApp Cloud API Configuration",
    details: "Configured Meta WABA ID waba_9918239012 and verified webhook endpoint.",
    timestamp: "Today, 01:10 PM",
    ipAddress: "192.168.1.10",
  },
  {
    id: "log-2",
    userId: "usr-emp-2",
    userName: "Karan Seth",
    userRole: "EMPLOYEE",
    action: "IMPORTED_LEADS",
    entityType: "LEAD",
    entityName: "Real Estate Leads – Punjab",
    details: "Imported 500 contacts from 500_leads.xlsx. Auto-fixed 18 duplicate numbers.",
    timestamp: "Today, 10:31 AM",
    ipAddress: "192.168.1.45",
  },
  {
    id: "log-3",
    userId: "usr-mgr-1",
    userName: "Rahul Kumar",
    userRole: "MANAGER",
    action: "REASSIGNED_LEAD",
    entityType: "LEAD",
    entityName: "Rahul Sharma (ABC Tech)",
    details: "Reassigned lead from Karan Seth to Priya Patel based on territory workload.",
    timestamp: "Today, 10:35 AM",
    ipAddress: "192.168.1.22",
  },
  {
    id: "log-4",
    userId: "usr-admin",
    userName: "Aman Sharma",
    userRole: "MAIN_ADMIN",
    action: "APPROVED_TEMPLATE",
    entityType: "TEMPLATE",
    entityName: "property_followup_punjab",
    details: "Approved company WhatsApp template submitted by Rahul Kumar.",
    timestamp: "Aug 23, 04:15 PM",
    ipAddress: "192.168.1.10",
  },
  {
    id: "log-5",
    userId: "usr-admin",
    userName: "Aman Sharma",
    userRole: "MAIN_ADMIN",
    action: "CREATED_CUSTOM_ROLE",
    entityType: "USER",
    entityName: "Senior Marketing Employee",
    details: "Configured custom permissions allowing template and campaign creation without delete rights.",
    timestamp: "Aug 22, 11:00 AM",
    ipAddress: "192.168.1.10",
  },
];

export const MOCK_AUTOMATIONS: Automation[] = [
  {
    id: "auto-1",
    name: "Response-Based 360° Follow-up Engine",
    description: "WhatsApp greeting ➔ Wait 2 Days ➔ AI analyzes response: if Interested ➔ notify manager & task; if No response ➔ fallback email.",
    status: "ACTIVE",
    category: "SALES",
    triggerType: "LEAD_CREATED",
    executionCount: 1240,
    successCount: 1218,
    failureCount: 22,
    lastRunAt: "5 minutes ago",
    createdById: "usr-admin",
    createdByName: "Aman Sharma",
    flowDefinition: {
      nodes: [
        {
          id: "node-1",
          type: "trigger",
          position: { x: 250, y: 50 },
          data: {
            label: "WHEN: Lead Ingested / Enrolled",
            type: "trigger",
            description: "Triggers on Excel import, Form submit, or Manual enrollment",
            config: { event: "LEAD_CREATED" },
          },
        },
        {
          id: "node-2",
          type: "action_assign",
          position: { x: 250, y: 180 },
          data: {
            label: "THEN: Assign Rep (Pod Round-Robin)",
            type: "action_assign",
            description: "Evenly distributes to manager's active team",
            config: { method: "Round-Robin", team: "North Pod" },
          },
        },
        {
          id: "node-3",
          type: "action_whatsapp",
          position: { x: 250, y: 310 },
          data: {
            label: "THEN: Send WhatsApp Template",
            type: "action_whatsapp",
            description: "Dispatches template 'lead_welcome_intro' via Official Meta Cloud API",
            config: { templateName: "lead_welcome_intro" },
          },
        },
        {
          id: "node-4",
          type: "delay",
          position: { x: 250, y: 440 },
          data: {
            label: "WAIT: Up to 2 Days for Response",
            type: "delay",
            description: "Listens for customer reply webhook",
            config: { duration: 2, unit: "days" },
          },
        },
        {
          id: "node-5",
          type: "condition",
          position: { x: 250, y: 570 },
          data: {
            label: "IF: Customer Replied?",
            type: "condition",
            description: "Branch YES ➔ AI Intent Classification; NO ➔ Fallback Email",
            config: { field: "hasReplied", operator: "==", value: true },
          },
        },
      ],
      edges: [
        { id: "e1-2", source: "node-1", target: "node-2", animated: true },
        { id: "e2-3", source: "node-2", target: "node-3", animated: true },
        { id: "e3-4", source: "node-3", target: "node-4", animated: true },
        { id: "e4-5", source: "node-4", target: "node-5", animated: true },
      ],
    },
  },
  {
    id: "auto-2",
    name: "AI Workshop & Webinar Auto-Reminders",
    description: "5-step journey: signup pass, calendar invite, 2-day alert, 2h WhatsApp link, post-event NPS.",
    status: "ACTIVE",
    category: "EVENTS",
    triggerType: "EVENT_REGISTERED",
    executionCount: 560,
    successCount: 558,
    failureCount: 2,
    lastRunAt: "22 mins ago",
    createdById: "usr-emp-3",
    createdByName: "Neha Roy",
    flowDefinition: {
      nodes: [
        {
          id: "w-1",
          type: "trigger",
          position: { x: 250, y: 50 },
          data: { label: "WHEN: Event Registered", type: "trigger", config: {} },
        },
        {
          id: "w-2",
          type: "action_whatsapp",
          position: { x: 250, y: 180 },
          data: { label: "THEN: Send Instant QR Ticket", type: "action_whatsapp", config: {} },
        },
      ],
      edges: [{ id: "we1-2", source: "w-1", target: "w-2", animated: true }],
    },
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "task-1",
    title: "Call Rahul Sharma to finalize website contract",
    description: "Customer replied 'Interested' to WhatsApp intro. High intent.",
    contactId: "cont-1",
    contactName: "Rahul Sharma",
    contactCompany: "ABC Technologies",
    dueDate: "Today, 02:00 PM",
    priority: "URGENT",
    status: "PENDING",
    assignedToId: "usr-emp-1",
    assignedToName: "Priya Patel",
    managerId: "usr-mgr-1",
  },
  {
    id: "task-2",
    title: "Send revised proposal to Aman Kapoor",
    description: "Include multi-branch CRM license option requested during meeting.",
    contactId: "cont-2",
    contactName: "Aman Kapoor",
    contactCompany: "Apex Infra",
    dueDate: "Today, 04:30 PM",
    priority: "HIGH",
    status: "PENDING",
    assignedToId: "usr-emp-1",
    assignedToName: "Priya Patel",
    managerId: "usr-mgr-1",
  },
  {
    id: "task-3",
    title: "Prepare Zoom demo for Sarah Jenkins",
    description: "Focus on Enterprise Webhook sync and BullMQ background workers.",
    contactId: "cont-3",
    contactName: "Sarah Jenkins",
    contactCompany: "Global Logistics",
    dueDate: "Tomorrow, 11:00 AM",
    priority: "MEDIUM",
    status: "PENDING",
    assignedToId: "usr-emp-4",
    assignedToName: "David Brown",
    managerId: "usr-mgr-2",
  },
];

export const MOCK_CHATS: Record<string, ChatMessage[]> = {
  "cont-1": [
    {
      id: "msg-1",
      contactId: "cont-1",
      channel: "WHATSAPP",
      direction: "OUTBOUND",
      status: "READ",
      senderName: "FlowDesk Automation",
      content: "Hi Rahul 👋 Thanks for your interest in our website services! We're reviewing your requirements. Are you looking to launch this month?",
      timestamp: "Today, 09:30 AM",
    },
    {
      id: "msg-2",
      contactId: "cont-1",
      channel: "WHATSAPP",
      direction: "INBOUND",
      status: "READ",
      senderName: "Rahul Sharma",
      content: "Yes, I am interested. Please share pricing and website proposal.",
      timestamp: "Today, 09:42 AM",
      aiIntent: "INTERESTED",
    },
    {
      id: "msg-3",
      contactId: "cont-1",
      channel: "WHATSAPP",
      direction: "OUTBOUND",
      status: "DELIVERED",
      senderName: "Priya Patel",
      content: "Hi Rahul, Priya here from the sales team! I will call you today at 2:00 PM to walk through the custom proposal.",
      timestamp: "Today, 10:05 AM",
    },
  ],
  "cont-2": [
    {
      id: "msg-201",
      contactId: "cont-2",
      channel: "WHATSAPP",
      direction: "OUTBOUND",
      status: "READ",
      senderName: "Priya Patel",
      content: "Hello Mr. Kapoor, I have prepared the CRM proposal for Apex Infra.",
      timestamp: "Yesterday, 04:15 PM",
    },
    {
      id: "msg-202",
      contactId: "cont-2",
      channel: "WHATSAPP",
      direction: "INBOUND",
      status: "READ",
      senderName: "Aman Kapoor",
      content: "Please send the updated pricing by 4:30 PM today so we can finalize.",
      timestamp: "Today, 09:00 AM",
      aiIntent: "QUESTION",
    },
  ],
};

export const MOCK_DEALS: Deal[] = [
  {
    id: "deal-1",
    title: "ABC Tech Website + WhatsApp Suite",
    contactId: "cont-1",
    contactName: "Rahul Sharma",
    company: "ABC Technologies",
    value: 150000,
    stage: "PROPOSAL",
    probability: 75,
    expectedCloseDate: "2026-09-05",
    assignedToName: "Priya Patel",
  },
  {
    id: "deal-2",
    title: "Apex Infra Multi-Channel Marketing",
    contactId: "cont-2",
    contactName: "Aman Kapoor",
    company: "Apex Infra Developers",
    value: 300000,
    stage: "NEGOTIATION",
    probability: 85,
    expectedCloseDate: "2026-08-31",
    assignedToName: "Priya Patel",
  },
  {
    id: "deal-3",
    title: "Global Logistics Enterprise Automation",
    contactId: "cont-3",
    contactName: "Sarah Jenkins",
    company: "Global Logistics Corp",
    value: 450000,
    stage: "DISCOVERY",
    probability: 40,
    expectedCloseDate: "2026-09-20",
    assignedToName: "David Brown",
  },
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: "cmp-1",
    name: "Festive Season Flash Promotion",
    channel: "WHATSAPP",
    segmentName: "Real Estate Leads – Punjab",
    status: "COMPLETED",
    totalRecipients: 2430,
    sentCount: 2430,
    deliveredCount: 2398,
    readCount: 2180,
    clickedCount: 940,
    repliedCount: 428,
    ownerId: "usr-emp-3",
    ownerName: "Neha Roy",
    managerId: "usr-mgr-1",
  },
  {
    id: "cmp-2",
    name: "Q3 Product Update & Feature Showcase",
    channel: "EMAIL",
    segmentName: "All Active Customers",
    status: "COMPLETED",
    totalRecipients: 5800,
    sentCount: 5800,
    deliveredCount: 5740,
    readCount: 3120,
    clickedCount: 1420,
    repliedCount: 180,
    ownerId: "usr-admin",
    ownerName: "Aman Sharma",
  },
];
